[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.poetry]
name = "dephell-archive"
version = "0.1.0"
authors = ["orsinium"]
description = "pathlib for archives"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.5"
attrs = "*"
